site_name: MobArenaDocs
theme:
  name: material
  logo: assets/logo.png
  palette:
    scheme: slate
    primary: blue
    accent: indigo
  features:
    - navigation.instant
    - navigation.tabs
