site_name: MobArenaDocs
theme:
  name: material
  logo: assets/creeper-head.svg
  palette:
    scheme: slate
    primary: blue
    accent: indigo
  features:
    - navigation.instant
    - navigation.tabs
