site_name: MobArena
theme:
  name: material
  logo: assets/logo.png
  palette:
    scheme: slate
    primary: blue
    accent: blue
  features:
    - navigation.instant
    - navigation.tabs
